addons:
  postgresql: '9.4'
before_script:
  - cp config/database.yml.sample config/database.yml
cache: bundler
language: ruby
rvm:
- 2.1.10
services:
  - postgresql
script:
  - bundle exec rubocop
  - bundle exec rake db:setup
  - bundle exec rspec
sudo: required
